### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'inputs'

### ISSUE THREAD

**Issue by wallacev** [poikilos/io_import_x#15]
Python: Traceback (most recent call last):
  File "C:\Users\Esmeralda\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_import_x-master__init__.py", line 237, in execute
    return import_x.load(self, context, **keywords)
  File "C:\Users\Esmeralda\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_import_x-master\import_x.py", line 1096, in load
    import_dXtree(rootTokens, item_file.name)
  File "C:\Users\Esmeralda\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_import_x-master\import_x.py", line 735, in import_dXtree
    child = importdXtree(getChilds(tokenname), file+"_"+tokenname, lvl=lvl+1)
  File "C:\Users\Esmeralda\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_import_x-master\import_x.py", line 680, in import_dXtree
    ob = getMesh(parentname, tokenname)
  File "C:\Users\Esmeralda\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_import_x-master\import_x.py", line 983, in getMesh
    mat_input = mat_shadernode.inputs[0]
AttributeError: 'NoneType' object has no attribute 'inputs'

Can't import .x files on my notebook
Mostly same specs, Python 3.10.5, Blender 3.5.1

On my desktop works fine, importing the same file and I can't figure why

**Comment by Poikilos** [comment]
See issue #13 and also please double check and reply with the Blender version on the other machine.

**Comment by wallacev** [comment]
Same version, downloaded from Steam, checked 2 times, can't figure why, through it was python version and installed the same on the notebook but the error its the same, computer working just fine 
![image](https://github.com/Poikilos/io_import_x/assets/18698901/c13a3008-cc87-4ee8-809e-6d051a25abb8)

**Comment by Poikilos** [comment]
Do you think maybe you have used a different renderer on the other machine? Are both set to Eevee or what? I'm not sure if that would affect the issue but I really can't imagine why it would work on one computer and not the other with the same Blender version and same file. Please provide the x file to me if it is ok to share, in case I can reproduce the issue and maybe if you provide a license such as if it is a Creative Commons file I even create a regression test.
