### ISSUE TITLE
AttributeError: 'Material' object has no attribute 'use_transparency'

### ISSUE THREAD

**Issue by Poikilos** [poikilos/io_import_x#4]
Importing a certain x file (that doesn't have alpha, apparently) raises an exception and the model import fails.
- `wget https://git.minetest.org/minetest-LOTR/Lord-of-the-Test/raw/branch/master/mods/lottmobs/models/horse_model.x` (also happens with the model of the same filename which is in Bucket_Game)

```
importing horse_model.x...
WARNING: There are 1 facemats but 82 faces.The faces length will be used and facemats[0] will be used for each.
Traceback (most recent call last):
  File "/home/owner/.config/blender/2.83/scripts/addons/io_import_x/__init__.py", line 237, in execute
    return import_x.load(self, context, **keywords)
  File "/home/owner/.config/blender/2.83/scripts/addons/io_import_x/import_x.py", line 1090, in load
    import_dXtree(rootTokens, item_file.name)
  File "/home/owner/.config/blender/2.83/scripts/addons/io_import_x/import_x.py", line 731, in import_dXtree
    child = import_dXtree(getChilds(tokenname), file_+"_"+tokenname, lvl=lvl+1)
  File "/home/owner/.config/blender/2.83/scripts/addons/io_import_x/import_x.py", line 731, in import_dXtree
    child = import_dXtree(getChilds(tokenname), file_+"_"+tokenname, lvl=lvl+1)
  File "/home/owner/.config/blender/2.83/scripts/addons/io_import_x/import_x.py", line 731, in import_dXtree
    child = import_dXtree(getChilds(tokenname), file_+"_"+tokenname, lvl=lvl+1)
  File "/home/owner/.config/blender/2.83/scripts/addons/io_import_x/import_x.py", line 678, in import_dXtree
    ob = getMesh(parentname, tokenname)
  File "/home/owner/.config/blender/2.83/scripts/addons/io_import_x/import_x.py", line 904, in getMesh
    mat.use_transparency = True
AttributeError: 'Material' object has no attribute 'use_transparency'
```

**Comment by Poikilos** [comment]
"Whether to use alpha is controlled by the [Blend Method](https://docs.blender.org/manual/en/2.90/render/eevee/materials/settings.html#blend-mode). As a replacement for reading `material.use_transparency`, try using `material.blend_method != 'OPAQUE'`." -scurest [Sep 20 '20 at 6:33](https://blender.stackexchange.com/a/195081) on blender.stackexchange.com

**Comment by Poikilos** [comment]
[Blender 2.8 changelog](https://docs.blender.org/api/blender2.8/change_log.html)
- Removed
  - use_transparency
  - transparency_method
  - alpha
  - specular_alpha

## Material in current API documentation
<https://docs.blender.org/api/current/bpy.types.Material.html>
